spring:
  main:
    banner-mode: "off"
  application:
    name: microservice-chassi
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    name: testdb
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update

server:
  port: 5555
  servlet:
    context-path: /onboardings/v1